### ISSUE TITLE
Unable to fetch parameters /fleet-provision/provision/templateName, /fleet-provision/provision/topic

### ISSUE THREAD

**Issue by thuan1091996** [NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160#7] opened 2024-03-19 10:02 UTC
# General Issue
- Failed to deploy on WSL2 - Win10

# Procedure
1. Update '**.envrc**' with appropriate credentials
2. Install Dependencies with `npm ci`
3. `./cli.sh generate-lambda-provision-certificate "uplink" "thingy91_provision_template"`
(In step 3 I choose a random topic and provisioning template name **"uplink"** and **"thingy91_provision_template"**)
4. `npx cdk bootstrap`
5.  `npx cdk deploy` ❌

# Question
Hello team,
I got the error when trying to deploy with `npx cdk deploy`. Could you please help me check the error in the attached log please, thank you. 

```
>>  npx cdk bootstrap
 ⏳  Bootstrapping environment aws://736336695270/ap-southeast-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.

 ✨ hotswap deployment skipped - no changes were detected (use --force to override)

 ✅  Environment aws://736336695270/ap-southeast-1 bootstrapped (no changes).


>> npx cdk deploy

✨  Synthesis time: 32.3s

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬────────────────────────────────────────────────────┬────────┬────────────────────────────────────────────────────┬────────────────────────────────────────────────────┬──────────────────────────────────────────────────────┐
│   │ Resource                                           │ Effect │ Action                                             │ Principal                                          │ Condition                                            │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ ${LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/Ser │ Allow  │ sts:AssumeRole                                     │ Service:lambda.amazonaws.com                       │                                                      │
│   │ viceRole.Arn}                                      │        │                                                    │                                                    │                                                      │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ ${fleet/role.Arn}                                  │ Allow  │ sts:AssumeRole                                     │ Service:iot.amazonaws.com                          │                                                      │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ ${provision/provision.Arn}                         │ Allow  │ lambda:InvokeFunction                              │ Service:iot.amazonaws.com                          │ "ArnLike": {                                         │
│   │                                                    │        │                                                    │                                                    │   "AWS:SourceArn": "${provision/topicRule.Arn}"      │
│   │                                                    │        │                                                    │                                                    │ }                                                    │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ ${provision/provision/ServiceRole.Arn}             │ Allow  │ sts:AssumeRole                                     │ Service:lambda.amazonaws.com                       │                                                      │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ ${provision/errorActionRole/iot-action-role.Arn}   │ Allow  │ sts:AssumeRole                                     │ Service:iot.amazonaws.com                          │                                                      │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ *                                                  │ Allow  │ logs:DeleteRetentionPolicy                         │ AWS:${LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a │                                                      │
│   │                                                    │        │ logs:PutRetentionPolicy                            │ /ServiceRole}                                      │                                                      │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic │ Allow  │ iot:Publish                                        │ AWS:${provision/errorActionRole/iot-action-role}   │                                                      │
│   │ /errors                                            │        │                                                    │                                                    │                                                      │
├───┼────────────────────────────────────────────────────┼────────┼────────────────────────────────────────────────────┼────────────────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ + │ arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:param │ Allow  │ ssm:GetParametersByPath                            │ AWS:${provision/provision/ServiceRole}             │                                                      │
│   │ eter/fleet-provision/lambdaClaim                   │        │                                                    │                                                    │                                                      │
└───┴────────────────────────────────────────────────────┴────────┴────────────────────────────────────────────────────┴────────────────────────────────────────────────────┴──────────────────────────────────────────────────────┘
IAM Policy Changes
┌───┬─────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                                                    │ Managed Policy ARN                                                             │
├───┼─────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
├───┼─────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${fleet/role}                                               │ arn:aws:iam::aws:policy/service-role/AWSIoTThingsRegistration                  │
├───┼─────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${provision/provision/ServiceRole}                          │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
└───┴─────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
fleet-provision: deploying... [1/1]
fleet-provision: creating CloudFormation changeset...

 ❌  fleet-provision failed: Error [ValidationError]: Unable to fetch parameters [/fleet-provision/provision/templateName,/fleet-provision/provision/topic] from parameter store for this account.
    at Request.extractError (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:46430)
    at Request.callListeners (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:89985)
    at Request.emit (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:89433)
    at Request.emit (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:196191)
    at Request.transition (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:189743)
    at AcceptorStateMachine.runTo (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:154615)
    at /home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:154945
    at Request.<anonymous> (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:190035)
    at Request.<anonymous> (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:196266)
    at Request.callListeners (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:90153) {
  code: 'ValidationError',
  time: 2024-03-19T09:48:36.270Z,
  requestId: '78554c32-09e2-47cd-9d08-3a6ff861cc43',
  statusCode: 400,
  retryable: false,
  retryDelay: 258.8522043103403
}

 ❌ Deployment failed: Error [ValidationError]: Unable to fetch parameters [/fleet-provision/provision/templateName,/fleet-provision/provision/topic] from parameter store for this account.
    at Request.extractError (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:46430)
    at Request.callListeners (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:89985)
    at Request.emit (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:89433)
    at Request.emit (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:196191)
    at Request.transition (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:189743)
    at AcceptorStateMachine.runTo (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:154615)
    at /home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:154945
    at Request.<anonymous> (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:190035)
    at Request.<anonymous> (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:196266)
    at Request.callListeners (/home/thuantm/projects/aws-iot-core-fleet-provisioning-with-nrf9160/node_modules/aws-cdk/lib/index.js:321:90153) {
  code: 'ValidationError',
  time: 2024-03-19T09:48:36.270Z,
  requestId: '78554c32-09e2-47cd-9d08-3a6ff861cc43',
  statusCode: 400,
  retryable: false,
  retryDelay: 258.8522043103403
}

Unable to fetch parameters [/fleet-provision/provision/templateName,/fleet-provision/provision/topic] from parameter store for this account.
```

**Comment by coderbyheart** [comment] 2024-03-19 10:07
Hei @thuan1091996, thank you for reporting this.

For some reason the SSM parameters `fleet-provision/provision/templateName,/fleet-provision/provision/topic` are not found.

I'll try to reproduce this.

**Comment by coderbyheart** [comment] 2024-03-19 10:47
Can you run this command and share the output?

`aws ssm get-parameters-by-path --recursive --path /fleet-provision`

I suspect that these values have not been set.

Can you then run 

`./cli.sh generate-lambda-provision-certificate "uplink" "thingy91_provision_template"`

again and then deploy again using `npx cdk deploy`?

**Comment by thuan1091996** [comment] 2024-03-19 10:59
Hello @coderbyheart,
Thank you for your prompt reply 
> Can you run this command and share the output?
> aws ssm get-parameters-by-path --recursive --path /fleet-provision
```
❯ aws ssm get-parameters-by-path --recursive --path /fleet-pro
{
    "Parameters": []
}
```
After I install and configure, the result from `aws ssm get-parameters-by-path --recursive --path /fleet-provision` still the same

> Can you then run
>./cli.sh generate-lambda-provision-certificate "uplink" "thingy91_provision_template"
> again and then deploy again using npx cdk deploy?

I re-ran but unfortunately, still unable to fetch the parameters

**Comment by coderbyheart** [comment] 2024-03-19 11:06
Thanks. It worked on Linux, so I'll try it on WSL now.

**Comment by coderbyheart** [comment] 2024-03-19 11:26
Which version of Windows 10 are you using?

**Comment by thuan1091996** [comment] 2024-03-19 14:26
Here is my environment
- Windows 10 Home, version: 22H2, OS build: 19045.4170
- WSL2 version:  2.1.5.0. Kernel version: 5.15.146.1-2, Ubuntu22.04.3 LTS

When I tried to re-run 
```
 ./cli.sh generate-lambda-provision-certificate "uplink" "thingy91_provision_template"
```
I got the following error
```
 >> ./cli.sh generate-lambda-provision-certificate "uplink" "thing91"

Creating policy fleet-provision-lambda-provision-policy
 ERROR  generate-lambda-provision-certificate <topic> <templateName> failed!
 ERROR  ResourceAlreadyExistsException: Policy cannot be created - name already exists (name=fleet-provision-lambda-provision-policy)

 >>           
```

**Comment by coderbyheart** [comment] 2024-03-19 16:19
> After I install and configure, the result from `aws ssm get-parameters-by-path --recursive --path /fleet-provision` still the same

Make sure your `AWS_DEFAULT_REGION` is also set to `ap-southeast-1` when you use the `aws` command, because it uses that environment variable instead of `AWS_REGION`.

I tried with with WSL2, Ubuntu 22.04 and it worked for me.

<img width="796" alt="Screenshot 2024-03-19 091211" src="https://github.com/NordicPlayground/aws-iot-core-fleet-provisioning-with-nrf9160/assets/188915/4a66b6f3-427d-4751-8bb3-c23446dbe0c1">

So, I'm not sure what's not working.
You could record what you are doing using https://asciinema.org/ and share it here, maybe I spot something.

Until then I'm closing this issue.

**Closed as completed by coderbyheart** 2024-03-19 16:19 UTC
Labels: bug, question

**Comment by thuan1091996** [comment] 2024-03-22 01:26
Hi @coderbyheart,
I switched to a new dev env and was able to generate the claim certificates and private key. Thank you for your help. Have a great day!
